import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import {
  X,
  Sparkles,
  FileText,
  Check,
  Copy,
  MapPin,
  Layers,
  Clock,
  Activity,
  FileCode,
  History,
} from 'lucide-react';

const EXPLANATION_SOURCES = {
  genai: {
    label: 'Gen AI Operator Briefing',
    note: 'Generated by Qwen2.5-72B-Instruct via the Hugging Face router.',
    color: 'var(--accent-cyan)',
    border: 'rgba(56, 189, 248, 0.25)',
    background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.1) 0%, rgba(168, 85, 247, 0.08) 100%)',
    Icon: Sparkles,
  },
  fallback: {
    label: 'Rule-based Operator Briefing',
    note: 'Deterministic template — the Gen AI model was unreachable, so no LLM text is being claimed here.',
    color: 'var(--sev-medium)',
    border: 'var(--sev-medium-border)',
    background: 'rgba(250, 204, 21, 0.06)',
    Icon: FileText,
  },
};

/** Factor rows: raw 0–1 factor for the bar, weighted contribution alongside it. */
const FACTORS = [
  {
    key: 'severity',
    label: '1. Severity Factor',
    color: 'var(--sev-critical)',
    evidence: () => 'Mapped from the reported severity level',
  },
  {
    key: 'recency',
    label: '2. Recency Factor (exponential decay)',
    color: 'var(--accent-cyan)',
    evidence: (f) => `${(f.age_minutes ?? 0).toFixed(1)} minutes old`,
  },
  {
    key: 'frequency',
    label: '3. Frequency Factor (5m burst window)',
    color: 'var(--sev-medium)',
    evidence: (f) => `${f.similar_events_in_window ?? 0} similar event(s) in the window`,
  },
  {
    key: 'blast_radius',
    label: '4. Blast Radius (cross-region / cross-service)',
    color: 'var(--accent-purple)',
    evidence: (f) =>
      `${f.services_in_region ?? 0} service(s) affected in this region, ` +
      `${f.regions_for_service ?? 0} region(s) for this service`,
  },
];

export default function EventDetailModal({ event, onClose, apiBase = '' }) {
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState('');
  const [activeTab, setActiveTab] = useState('analysis'); // 'analysis' | 'metadata' | 'audit'
  const [auditEntries, setAuditEntries] = useState([]);
  const [loadingAudit, setLoadingAudit] = useState(false);
  const [auditError, setAuditError] = useState('');
  const [detail, setDetail] = useState(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const copyTimer = useRef(null);
  const eventId = event?.id;

  // Escape-to-close. The modal previously trapped the operator until they
  // found the small × — on a phone that is a real usability bug.
  useEffect(() => {
    const onKeyDown = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [onClose]);

  useEffect(() => () => clearTimeout(copyTimer.current), []);

  // Audit trail for this event. The dependency used to be the whole `event`
  // object, which App replaces on every 8s poll — so this refetched the audit
  // trail (and reset the loading spinner) four times a minute for no reason.
  useEffect(() => {
    if (!eventId) return;
    const controller = new AbortController();
    setLoadingAudit(true);
    setAuditError('');

    fetch(`${apiBase}/api/audit?event_id=${encodeURIComponent(eventId)}&limit=50`, {
      signal: controller.signal,
    })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        setAuditEntries(await res.json());
      })
      .catch((err) => {
        if (err.name === 'AbortError') return;
        console.error('Failed to load event audit', err);
        setAuditError('Could not load the audit trail for this event.');
      })
      .finally(() => setLoadingAudit(false));

    return () => controller.abort();
  }, [eventId, apiBase]);

  // Ask the detail endpoint for this one event. GET /api/briefings/{id} waits
  // briefly for genuine Gen AI text instead of serving the template, and it was
  // dead code before this — nothing in the UI ever called it.
  useEffect(() => {
    if (!eventId) return;
    const controller = new AbortController();
    setLoadingDetail(true);
    setDetail(null);

    fetch(`${apiBase}/api/briefings/${encodeURIComponent(eventId)}`, { signal: controller.signal })
      .then(async (res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        setDetail(await res.json());
      })
      .catch((err) => {
        if (err.name === 'AbortError') return;
        // Non-fatal: the list payload already carries a usable explanation.
        console.error('Failed to load event detail', err);
      })
      .finally(() => setLoadingDetail(false));

    return () => controller.abort();
  }, [eventId, apiBase]);

  // Score and rank come from the live poll (they change as weights are tuned);
  // the explanation is taken from whichever source actually reached the model.
  const view = useMemo(() => {
    if (!event) return null;
    if (!detail || event.explanation_source === 'genai' || !detail.explanation) return event;
    return {
      ...event,
      explanation: detail.explanation,
      explanation_source: detail.explanation_source,
    };
  }, [event, detail]);

  const copyJson = useCallback(async () => {
    const json = JSON.stringify(view, null, 2);
    setCopyError('');
    try {
      // navigator.clipboard is undefined on non-HTTPS origins — i.e. exactly
      // when a phone hits this dashboard over plain http on the LAN.
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(json);
      } else {
        const textarea = document.createElement('textarea');
        textarea.value = json;
        textarea.style.position = 'fixed';
        textarea.style.opacity = '0';
        document.body.appendChild(textarea);
        textarea.select();
        const ok = document.execCommand('copy');
        document.body.removeChild(textarea);
        if (!ok) throw new Error('execCommand returned false');
      }
      setCopied(true);
      clearTimeout(copyTimer.current);
      copyTimer.current = setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Clipboard write failed', err);
      setCopyError('Clipboard blocked — use the Raw Payload tab');
      clearTimeout(copyTimer.current);
      copyTimer.current = setTimeout(() => setCopyError(''), 3000);
    }
  }, [view]);

  if (!view) return null;

  const score = typeof view.score === 'number' ? view.score : 0;
  const bd = view.score_breakdown || {};
  const factors = view.score_factors || {};
  const meta = EXPLANATION_SOURCES[view.explanation_source] || EXPLANATION_SOURCES.fallback;
  const { Icon: SourceIcon } = meta;

  const tabs = [
    { id: 'analysis', label: 'Score & Explanation', Icon: Activity },
    { id: 'metadata', label: 'Raw Payload', Icon: FileCode },
    { id: 'audit', label: `Event Audit (${auditEntries.length})`, Icon: History },
  ];

  return (
    <div
      role="presentation"
      // Backdrop click closes. Guarded on currentTarget so a click that started
      // inside the panel (e.g. dragging to select JSON) does not close it.
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 100,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
        background: 'rgba(4, 7, 13, 0.82)',
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
      }}
    >
      <div
        className="glass-panel"
        role="dialog"
        aria-modal="true"
        aria-label={`Incident detail: ${view.title}`}
        style={{
          width: '100%',
          maxWidth: '750px',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          border: '1px solid var(--border-medium)',
          boxShadow: '0 25px 60px -15px rgba(0, 0, 0, 0.7)',
          animation: 'fadeIn 0.2s ease-out',
        }}
      >
        {/* Modal Header */}
        <div style={{
          padding: '18px 22px',
          borderBottom: '1px solid var(--border-subtle)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '10px',
          background: 'rgba(15, 23, 42, 0.6)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', minWidth: 0 }}>
            <span style={{
              fontWeight: 800,
              fontSize: '0.9rem',
              padding: '2px 8px',
              borderRadius: '6px',
              background: 'rgba(56, 189, 248, 0.2)',
              color: 'var(--accent-cyan)',
              whiteSpace: 'nowrap',
            }}>
              RANK #{view.rank || '—'}
            </span>
            <span className="mono" style={{
              fontSize: '0.8rem',
              color: 'var(--text-muted)',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
            }}>
              {view.id}
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
            <button
              onClick={copyJson}
              title={copyError || 'Copy this event as JSON'}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                padding: '6px 12px',
                borderRadius: '6px',
                border: '1px solid var(--border-subtle)',
                background: 'rgba(255, 255, 255, 0.05)',
                color: copyError ? 'var(--sev-critical)' : 'var(--text-secondary)',
                fontSize: '0.75rem',
                cursor: 'pointer'
              }}
            >
              {copied ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
              <span className="hide-on-mobile">
                {copyError ? 'Copy blocked' : copied ? 'Copied' : 'Copy JSON'}
              </span>
            </button>

            <button
              onClick={onClose}
              aria-label="Close detail view"
              style={{
                background: 'rgba(255, 255, 255, 0.05)',
                border: 'none',
                color: 'var(--text-secondary)',
                padding: '6px',
                borderRadius: '6px',
                cursor: 'pointer',
                display: 'flex',
              }}
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Modal Subheader: Title & Tags */}
        <div style={{ padding: '20px 22px 14px', borderBottom: '1px solid var(--border-subtle)' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '12px', lineHeight: 1.35 }}>
            {view.title}
          </h2>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
            <span className={`badge badge-${view.severity}`}>{view.severity}</span>
            <span className="badge badge-source">{view.source}</span>
            {view.region && (
              <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <MapPin size={13} color="var(--accent-cyan)" /> {view.region}
              </span>
            )}
            {view.service && (
              <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <Layers size={13} color="var(--accent-purple)" /> {view.service}
              </span>
            )}
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '4px' }}>
              <Clock size={13} />
              {Number.isNaN(new Date(view.timestamp).getTime())
                ? 'unknown time'
                : new Date(view.timestamp).toLocaleString()}
            </span>
          </div>

          {/* Modal Tabs */}
          <div style={{ display: 'flex', gap: '6px', marginTop: '16px', flexWrap: 'wrap' }}>
            {tabs.map(({ id, label, Icon }) => (
              <button
                key={id}
                onClick={() => setActiveTab(id)}
                aria-pressed={activeTab === id}
                style={{
                  padding: '6px 14px',
                  borderRadius: '6px',
                  border: 'none',
                  background: activeTab === id ? 'rgba(56, 189, 248, 0.2)' : 'rgba(255, 255, 255, 0.04)',
                  color: activeTab === id ? 'var(--accent-cyan)' : 'var(--text-secondary)',
                  fontSize: '0.8rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                <Icon size={14} />
                <span>{label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div style={{ padding: '20px 22px', overflowY: 'auto', flex: 1 }}>
          {activeTab === 'analysis' && (
            <div>
              {/* Explanation callout, labelled by its real provenance */}
              <div style={{
                background: meta.background,
                border: `1px solid ${meta.border}`,
                borderRadius: 'var(--radius-md)',
                padding: '16px',
                marginBottom: '20px',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                  <SourceIcon size={18} color={meta.color} />
                  <span style={{ fontWeight: 700, fontSize: '0.85rem', color: meta.color, letterSpacing: '0.04em', textTransform: 'uppercase' }}>
                    {meta.label}
                  </span>
                  {loadingDetail && (
                    <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                      checking for fresh Gen AI text...
                    </span>
                  )}
                </div>
                <p style={{ fontSize: '0.95rem', color: '#f1f5f9', lineHeight: 1.6 }}>
                  {view.explanation || 'Generating explanation...'}
                </p>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '8px' }}>
                  {meta.note}
                </div>
              </div>

              {/* Total Score Summary */}
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                gap: '12px',
                padding: '14px 18px',
                background: 'rgba(15, 23, 42, 0.6)',
                borderRadius: 'var(--radius-md)',
                border: '1px solid var(--border-subtle)',
                marginBottom: '16px'
              }}>
                <div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600 }}>COMPOSITE RANK SCORE</div>
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Weighted sum of 4 dimensions (0.0 to 1.0)</div>
                </div>
                <div className="mono" style={{ fontSize: '1.75rem', fontWeight: 800, color: 'var(--accent-cyan)' }}>
                  {score.toFixed(4)}
                </div>
              </div>

              {/* Multi-factor Score Breakdown */}
              <h4 style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '4px' }}>
                Multi-Factor Breakdown
              </h4>
              <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
                Bars show the raw 0–100% factor value. &ldquo;Contributes&rdquo; is that factor
                after its ranking weight is applied — the four contributions sum to the score above.
              </p>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                {FACTORS.map(({ key, label, color, evidence }) => {
                  // The bar used to be `min(weighted * 250, 100)%` — a fudge factor
                  // that made a 0.40 weighted value look like a full bar. The raw
                  // factor is already normalised to 0–1, so use it directly.
                  const raw = factors[key] ?? 0;
                  const weighted = bd[key] ?? 0;
                  return (
                    <div key={key} style={{ background: 'rgba(255, 255, 255, 0.02)', padding: '10px 14px', borderRadius: '8px', border: '1px solid var(--border-subtle)' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', gap: '10px', fontSize: '0.8rem', marginBottom: '6px' }}>
                        <span style={{ color, fontWeight: 600 }}>{label}</span>
                        <span className="mono" style={{ color: 'var(--text-main)', fontWeight: 600, whiteSpace: 'nowrap' }}>
                          {(raw * 100).toFixed(0)}%
                        </span>
                      </div>
                      <div style={{ width: '100%', height: '6px', background: '#1e293b', borderRadius: '999px', overflow: 'hidden' }}>
                        <div style={{
                          width: `${Math.max(0, Math.min(raw * 100, 100))}%`,
                          height: '100%',
                          background: color,
                          borderRadius: '999px',
                          transition: 'width 0.3s ease',
                        }} />
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', gap: '10px', marginTop: '6px', fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                        <span>{evidence(factors)}</span>
                        <span className="mono" style={{ whiteSpace: 'nowrap' }}>
                          contributes {weighted.toFixed(4)}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {activeTab === 'metadata' && (
            <pre className="mono" style={{
              background: '#090d16',
              padding: '16px',
              borderRadius: '8px',
              border: '1px solid var(--border-subtle)',
              fontSize: '0.8rem',
              color: '#a5f3fc',
              overflowX: 'auto',
              lineHeight: 1.5,
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
            }}>
              {JSON.stringify(view, null, 2)}
            </pre>
          )}

          {activeTab === 'audit' && (
            <div>
              {loadingAudit ? (
                <div style={{ textAlign: 'center', padding: '20px', color: 'var(--text-muted)' }}>Loading audit trail...</div>
              ) : auditError ? (
                <div style={{ textAlign: 'center', padding: '20px', color: 'var(--sev-critical)' }}>{auditError}</div>
              ) : auditEntries.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '20px', color: 'var(--text-muted)' }}>No audit events logged for this item yet.</div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {auditEntries.map((entry, idx) => (
                    <div key={`${entry.timestamp}-${idx}`} style={{
                      padding: '10px 14px',
                      borderRadius: '8px',
                      background: 'rgba(255, 255, 255, 0.02)',
                      border: '1px solid var(--border-subtle)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      gap: '10px',
                      flexWrap: 'wrap',
                      fontSize: '0.8rem'
                    }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
                        <span className="badge badge-source" style={{ textTransform: 'uppercase', color: 'var(--accent-cyan)' }}>
                          {String(entry.action || '').replaceAll('_', ' ')}
                        </span>
                        <span style={{ color: 'var(--text-secondary)' }}>{entry.detail}</span>
                      </div>
                      <span className="mono" style={{ color: 'var(--text-muted)', fontSize: '0.7rem' }}>
                        {new Date(entry.timestamp).toLocaleTimeString()}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
